# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fiksu Kitchen Timer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON'
  # Pods for Fiksu Kitchen Timer

  target 'Fiksu Kitchen TimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fiksu Kitchen TimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
